bot:
  name: elanplusbot
  token: 6576821364:AAHfy6N_c2tnTxgErii81yG8TvS1OT7tsWM
spring:
  datasource:
    username: postgres
    password: 321678
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/elan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true